/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FeatureVector {
  severeFines: number
  mediumFines: number
  totalKm: number
  latePayments: number
  customerAge: number
  vehicleAge: number
  accidents: number
  maintenanceCount: number
  heavyUseCount: number
}
export interface SimulationResult {
  lossProbability: number
  expectedLoss: number
  confidenceInterval95: Array<number>
}
export interface RiskEvent {
  timestamp: number
  eventType: string
  severity: string
  value?: number
}
export interface Customer {
  id: string
  age: number
  relationshipYears: number
  paymentHistory: Array<number>
}
export interface Vehicle {
  id: string
  year: number
  category: string
  estimatedMileage: number
}
export interface RiskReportResponse {
  customerId: string
  vehicleId: string
  features: FeatureVector
  score: number
  simulation: SimulationResult
}
export interface BatchScoreStats {
  meanScore: number
  stdDev: number
  min: number
  max: number
}
export interface TemporalAggregation {
  lastMonth: number
  lastQuarter: number
  lastYear: number
}
export interface AnalyticsSummary {
  totalEvents: number
  eventsByCategory: Record<string, number>
  temporalAggregation: TemporalAggregation
  averageTimeBetweenEventsDays: number
}
export declare function analyzeCustomerHistory(customerId: string, vehicleId: string, historySize: number, seed?: number | undefined | null): AnalyticsSummary
export declare function generateRiskReport(customerId: string, vehicleId: string, historySize: number, simulationIterations: number, seed: number | undefined | null, customer: Customer, vehicle: Vehicle): RiskReportResponse
export declare function batchScoreAnalysis(count: number, seed?: number | undefined | null): BatchScoreStats
export declare function calculateRiskScore(features: FeatureVector): number
